* Внедрение и поддержка компьютерных систем
:PROPERTIES:
 :ANKI_DECK: Внедрение и поддержка компьютерных систем
:END:
** Что характеризует наш ПК?
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670064912344
  :END:
*** Текст

Что характеризует наш ПК?

- {{c1::Производительность и быстродействие::...}}
  возможность компьютера обрабатывать большие объемы информации.
  2 основных компонента, определяющих быстродействие: {{c1::Процессор и оперативная память::...}}
- {{c2::Скорость доступа к оперативной памяти::...}}
- {{c3::Производительность, быстродействие ЦП::...}}
- {{c4::Тактовая частота, частота синхронизации::...}}
  - {{c4::число тактов процессора за одну секунду.::...}}
  - {{c4::число обрабатываемых за секунду импульсов, которые синхронизируют работу узлов компьютера.::...}}
*** Дополнительно

** Такт?
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670066793825
  :END:

*** Текст
{{c1::Такт::...}} — {{c2::промежуток времени, за который выполняется элементарная операция.::...}}

*** Дополнительно

** Такт?
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670066794107
  :END:

*** Текст
{{c1::Разрядность ЦП::...}} —  {{c2::Максимальная длина двоичного кода, который может быть обработан и передан процессору целиком.::...}}

*** Дополнительно

** Кэш? 
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670066794323
  :END:
*** Текст
{{c1::Кэш-память первого уровня::...}} — {{c2::сверхоперативная память.::...}}

*** Дополнительно

** Время доступа 
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670066794605
  :END:
*** Текст
{{c1::Время доступа::...}} — {{c2::определяется быстродействием оперативной памяти, то есть это минимальный период времени необходимый для считывания или записи минимальной порции информации.::...}}

*** Дополнительно

** Объем памяти
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670066794930
  :END:
*** Текст
{{c1::Объём памяти (ёмкость)::...}} — {{c2::максимальное кол-во информации, 
которое может храниться в памяти одновременно.::...}}

*** Дополнительно

** Плотность записи
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670066795179
  :END:
*** Текст
{{c1::Плотность записи (к внешним накопителям)::...}} — {{c2::объём информации, 
записанный на единице длины дорожки. (бит/мм)::...}}

*** Дополнительно

** Скорость обмена информации 
  :PROPERTIES:
  :ANKI_NOTE_TYPE: С пропусками
  :ANKI_NOTE_ID: 1670066795466
  :END:
*** Текст
{{c1::Скорость обмена информации::...}} — {{c2::скорость записи и считывания на носитель, который определяется скоростью вращения или перемещения этого носителя.::...}}

*** Дополнительно

